version: 1
disable_existing_loggers: false

processors:
  - structlog.stdlib.add_log_level
  - structlog.stdlib.add_logger_name
  - structlog.processors.TimeStamper(fmt="iso")
  - structlog.processors.StackInfoRenderer
  - structlog.processors.format_exc_info
  - structlog.dev.ConsoleRenderer

level: INFO
